### ISSUE TITLE
24/12层RoBERTa模型的PyTorch版有release计划吗

### ISSUE THREAD

**Issue by bigrat911** [brightmart/roberta_zh#1]
如题，谢谢

**Comment by l11x0m7** [comment]
+1，希望能和pytorch版本训练出来中文模型进行对比，确认是否有gap

**Comment by brightmart** [comment]
有的 @bigrat911

**Comment by guoday** [comment]
可参考https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline 转化该项目的tf模型为pytorch模型

**Comment by brightmart** [comment]
已提供，请查收
