### ISSUE TITLE
[question] Pretrain longer 

### ISSUE THREAD

**Issue by lsq357** [brightmart/roberta_zh#10]
感谢开源!

如果我没算错的话，RoBERTa-zh-Large跑了3epoch +（8k * 100k / 2.5 亿)）  

在roberta原始论文的里面看到,没加dynamic mask的bert大约跑了40epoch
![image](https://user-images.githubusercontent.com/13764760/64482952-2190a680-d22d-11e9-827e-9a8d6aec1022.png)

所以可能训练更长的时间（500k/1m step）对下游任务效果会更好？
有进一步训练的计划吗？

**Comment by brightmart** [comment]
有的，模型还在继续训练中；如果收敛更好或对下游任务效果更好，这两天就会更新上来。

**Comment by lsq357** [comment]
期待
