### ISSUE TITLE
请问有国内链接吗，翻墙下载速度太慢了，谢谢！

### ISSUE THREAD

**Issue by TPF2017** [brightmart/roberta_zh#11]
https://drive.google.com/open?id=1W3WgPJWGVKlU9wpUYsdZuurAIFKvrl_Y
https://drive.google.com/file/d/1cg3tVKPyUEmiI88H3gasqYC4LV4X8dNm/view?usp=sharing

**Comment by brightmart** [comment]
好的。知道有比百度网盘更好的文件存储方式吗？

**Comment by TPF2017** [comment]
百度网盘就挺好的。

**Comment by brightmart** [comment]
已经添加百度网盘地址，Readme.md
或 ：https://pan.baidu.com/s/1Rk_QWqd7-wBTwycr91bmug

可以告知下游任务效果？
