### ISSUE TITLE
可以增加xlnet的在这两个数据集上的对比吗？

### ISSUE THREAD

**Issue by RyanHuangNLP** [brightmart/roberta_zh#13]
[xlnet chinese](https://github.com/ymcui/Chinese-PreTrained-XLNet)

**Comment by brightmart** [comment]
好的，网友提供了一个在情感分析公开任务上的效果对比，见ReadMe.md
![image](https://user-images.githubusercontent.com/19634224/64490418-2be38c80-d28f-11e9-8d7a-11a76b2c63b1.png)
