### ISSUE TITLE
下载RoBERTa-zh-Large总是提示网页走丢

### ISSUE THREAD

**Issue by haosiqing** [brightmart/roberta_zh#14]
下载RoBERTa-zh-Large总是提示网页走丢，下载不了，这是什么原因呢？有什么其他办法可以下载吗？

**Comment by brightmart** [comment]
可以下载的。这个走丢，只是预览不了。有下载的按钮，可以下载的。
![image](https://user-images.githubusercontent.com/19634224/64486912-1dcd4600-d266-11e9-803b-3444593df5de.png)

**Comment by brightmart** [comment]
你点【下载】

**Comment by haosiqing** [comment]
> 你点【下载】
 
![image](https://user-images.githubusercontent.com/50686292/64489014-1c5d4700-d281-11e9-8596-c3a7339bf2f8.png)

非常感谢您的回复。我点开网页是这样的，有时显示是走丢，也没有下载的按钮。我换了其他的浏览器和电脑试了也是一样的情况。

**Comment by brightmart** [comment]
你是否可以科学上网呢或访问外网，如google？

**Comment by haosiqing** [comment]
> 你是否可以科学上网呢或访问外网，如google？

好像是不可以，那请问有没有其他途径可以下载呢

**Comment by brightmart** [comment]
已经添加百度网盘地址，Readme.md 
或 ：https://pan.baidu.com/s/1Rk_QWqd7-wBTwycr91bmug
