### ISSUE TITLE
不能使用tf.train.load_variable函数来加载模型吗？

### ISSUE THREAD

**Issue by RingoTC** [brightmart/roberta_zh#15]
使用tf.train.load_variable函数加载模型，得到错误：
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ../roeberta_zh_L-24_H-1024_A-16/bert_model.ckpt

[keras-bert](https://github.com/CyberZHG/keras-bert)

**Comment by wang001** [comment]
文件名不对吧，bert_model.ckpt换成roberta_l24_large_model试试
