### ISSUE TITLE
想尝试转换，用tf.train.list_variables(init_checkpoint)加载模型报错

### ISSUE THREAD

**Issue by wang001** [brightmart/roberta_zh#19]
bert-wwm-ext就可以正常使用，这个不可以。

**Comment by brightmart** [comment]
看看这个：https://github.com/brightmart/roberta_zh/issues/15
应该是文件名的问题

**Comment by wang001** [comment]
就是我告诉他文件名不对的。。。。。我发现在执行这行的时候，磁盘在疯狂写入，然后就没有任何异常的退出。

**Comment by wang001** [comment]
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> init_checkpoint = "F:/pretrain/chinese_wwm_ext_L-12_H-768_A-12/bert_model.ckpt"
>>> init_vars = tf.train.list_variables(init_checkpoint)
>>> init_checkpoint = "F:/pretrain/roeberta_zh_L-24_H-768_A-12/checkpoint"
>>> init_vars = tf.train.list_variables(init_checkpoint)
上面那次成功加载，第二次list_variables就崩溃退出了

**Comment by wang001** [comment]
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> init_checkpoint = "F:/pretrain/roeberta_zh_L-24_H-1024_A-16/roberta_l24_large_model"
>>> init_vars = tf.train.list_variables(init_checkpoint)
会直接退出python

**Comment by wang001** [comment]
抱歉，可能是我的tensorflow有问题，虽然能正常跑代码，但是在别人的电脑上没有问题

**Comment by wang001** [comment]
本来是1.14.0的。换成1.12.0就可以了
