### ISSUE TITLE
加载pytorch模型错误

### ISSUE THREAD

**Issue by Benjamin-zhangjb** [brightmart/roberta_zh#20]
我使用这行加载模型时出错model_bert.load_state_dict(torch.load(init_checkpoint, map_location='cpu'))。

我修改成这个之后model_bert.load_state_dict(torch.load(init_checkpoint),strict=False)
模型可以使用但是效果很差。

**Comment by brightmart** [comment]
你使用的超参数是怎么样的能贴出来吗，strict是做什么的，batch size多少？ 

pytorch怎么样的，看看能不能参考一下这个https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline

**Comment by Benjamin-zhangjb** [comment]
我只直接使用使用模型的时候出现了这个问题
![image](https://user-images.githubusercontent.com/37786414/64579386-4f085c00-d3b5-11e9-88cf-876419415ffe.png)

**Comment by Benjamin-zhangjb** [comment]
![image](https://user-images.githubusercontent.com/37786414/64579414-68a9a380-d3b5-11e9-8454-8d2675781fa6.png)

**Comment by Benjamin-zhangjb** [comment]
![image](https://user-images.githubusercontent.com/37786414/64579441-8aa32600-d3b5-11e9-9db2-ef443da04353.png)

**Comment by ewrfcas** [comment]
怀疑要用model_bert.bert.load_state_dict(torch.load(init_checkpoint, map_location='cpu'))
@zhangjinagbo也许代码应该更新一下，老的pytorch-transformer读取会有问题

**Comment by Benjamin-zhangjb** [comment]
怎么更新下呢？求指教

**Comment by ewrfcas** [comment]
就是参考https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline 就可以了

**Comment by Benjamin-zhangjb** [comment]
网址链接失效了。。

**Comment by Benjamin-zhangjb** [comment]
ok了

**Comment by Benjamin-zhangjb** [comment]
那我先看下  谢谢啦
