### ISSUE TITLE
关于BPE

### ISSUE THREAD

**Issue by ArthurRizar** [brightmart/roberta_zh#21]
你好，我想问一下，这个模型应该没有加BPE吧，我看原版roBERTa是使用了BPE来做tokenizer

PS： 貌似roBERTa_12L的下载链接挂了

**Comment by brightmart** [comment]
中文可能不需要额外用BPE，因为中文的字已经非常独立了，不像英文有词根、词缀、时态等，可以将一个单词进一步切分。roBERTa_12L加上去了。

**Comment by MrRace** [comment]
@brightmart RoBERTa是使用BBPE，是 Byte-level BPE，并不是字符gram，而是字节级的gram。所以，这里发布的中文的RoBETa是使用WordPiece？

**Comment by MrRace** [comment]
@brightmart 原版RoBERTa 是使用BBPE吧？即Byte-Level BPE。这里发布的中文RoBERTa与BERT一样都是WordPiece吧？
