### ISSUE TITLE
关于预训练的embedding

### ISSUE THREAD

**Issue by beamind** [brightmart/roberta_zh#25]
请问预训练的embedding包含三部分(word embedding, position embedding, segment embedding)还是两部分(word embedding, position embedding)？谢谢！

**Comment by brightmart** [comment]
包含三部分(word embedding, position embedding, segment embedding)，但是segment embedding的每个字值都是一样的。这个有什么影响，有什么建议？

**Comment by beamind** [comment]
感谢解答！我也不知道有什么影响，就是看到checkpoint里面有segment embedding的参数，就好奇来确认一下。

**Comment by zhezhaoa** [comment]
您好
关于segment embedding的每个字值都是一样的
它们的每个值都是0还是都是1？

**Comment by brightmart** [comment]
好像是1，具体指可能不重要的，既然都是一样的。
