### ISSUE TITLE
24层base版(roberta_l24_zh_base）是用于bert的么？

### ISSUE THREAD

**Issue by qblyy** [brightmart/roberta_zh#3]
24层base版(roberta_l24_zh_base）是用于bert的么？解压后和fairseq使用的格式好像不一样。能给个简单的例子么？谢谢

**Comment by brightmart** [comment]
这个是用于bert的tensorflow版本。使用方法见：https://github.com/google-research/bert

**Comment by brightmart** [comment]
加载的例子，已经添加，请查看。
