### ISSUE TITLE
请问一下，你的代码跟bert代码除了在预处理阶段，在其它地方有区别？

### ISSUE THREAD

**Issue by yiyele** [brightmart/roberta_zh#30]

**Comment by brightmart** [comment]
还取消了next sentence prediction任务呢

**Comment by brightmart** [comment]
还取消了next sentence prediction任务呢

**Comment by nickchiang5121** [comment]
請問有加入"动态掩码"在run_pretraining.py嗎？
https://www.jiqizhixin.com/articles/2019-07-30-7
