### ISSUE TITLE
请教一下处理预训练数据的大致策略？

### ISSUE THREAD

**Issue by fengzuo97** [brightmart/roberta_zh#31]
最近在做bert模型蒸馏，准备使用作者开源的另一个中文语料库。训练数据的处理应该和作者训练roberta是一样的，取消了预测next sentence的预训练，所以训练数据只需要单独的句子就行。对于一篇长新闻的语料来说，我是以句号为分割，得到每一句话作为训练数据，还是尽可能满足长度接近512个字符的多个连续的句子作为一条训练数据，后面一种处理方法会遇到一些问题，比如最后不是以句号结尾，语义不完整，如果要处理，会复杂很杂。所以想请教下训练roberta时处理预训练数据的策略？

**Comment by brightmart** [comment]
可以结合你自己任务的长度来定。假设你的任务的长度为256，那么你预训练的长度也可以设置为256。

第一步生成训练数据的时候，可以按照一个句子为一行的方式；

在处理成训练实例的时候，可以从多个句子中取，直到256为止。少量超过的部分256的部分按照句号、逗号截取掉。

**Comment by fengzuo97** [comment]
谢谢

**Comment by brightmart** [comment]
更新了训练数据生成，请参考；如发现问题，请指出。
