### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by HongyanJiao** [brightmart/roberta_zh#34]
您好
我之前用bert-base-chinese设置的batch size是32,现在用pytorch版本的roberta large,batch size设置为4还会出现显存不够的问题.pytorch的使用应该没问题,在小的数据集上跑通了,请问roberta large比bert-base-chinese要大多少呢

**Comment by brightmart** [comment]
![image](https://user-images.githubusercontent.com/19634224/65383834-5cc2c780-dd4d-11e9-82d2-dba496a53b10.png)
在12G的显存上，序列长度和batch_size最大支持的配置参考这个。

 Large: 340M parameters vs Base: 110M parameters
