### ISSUE TITLE
[CLS],[SEP]

### ISSUE THREAD

**Issue by HongyanJiao** [brightmart/roberta_zh#35]
您好
我是用huggingface的pytorch代码https://github.com/huggingface/pytorch-transformers。但是我 设置了add_special_tokens=True，运行的时候却总是出错：
A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding.
并且忽略这个问题的话，运行之后的效果也远不如bert

**Comment by HongyanJiao** [comment]
![无标题](https://user-images.githubusercontent.com/44488820/65386056-4296e280-dd69-11e9-9d97-27452924a7ad.png)

**Comment by Vimos** [comment]
他们的special token不一样，个数也不一样，所以预处理要写的兼容才行。

不过这个repo不是用BERT加载吗？应该不使用Roberta加载

**Comment by HongyanJiao** [comment]
> 他们的special token不一样，个数也不一样，所以预处理要写的兼容才行。
> 
> 不过这个repo不是用BERT加载吗？应该不使用Roberta加载

tokenization部分是用huggingface提供的bert, Model部分也需要用BERT加载吗,我的Model部分用的是Roberta的

**Comment by Vimos** [comment]
我遇到过同样错误，是因为自己使用了`[CLS]`和`[SEP]`，实际上类的默认是`bos_token="<s>", eos_token="</s>", sep_token="</s>",
                 cls_token="<s>"`
之后复制了`run_glue`里面的预处理，就正常了

**Comment by HongyanJiao** [comment]
> 我遇到过同样错误，是因为自己使用了`[CLS]`和`[SEP]`，实际上类的默认是`bos_token="<s>", eos_token="</s>", sep_token="</s>", cls_token="<s>"`
> 之后复制了`run_glue`里面的预处理，就正常了

谢谢,我试一下
