### ISSUE TITLE
请问能否在所有权重中都把mlm部分带上？

### ISSUE THREAD

**Issue by bojone** [brightmart/roberta_zh#38]
做生成类任务，mlm是很重要的，能够极大地加速收敛。

参考： https://kexue.fm/archives/6933

我从百度云下载了RoBERTa_zh_L12的tensorflow版本，发现没有mlm的权重，不知道哪些版本有？建议有时间的话都加上比较好。

**Comment by brightmart** [comment]
苏剑林，你好。你可以试一试这个，你个有mlm的权重：https://drive.google.com/file/d/1MmVWOGTsCdeUMfeCePDcatsui9zL3lND/view

**Comment by sunyilgdx** [comment]
请问一下这个TF版本的能转成Pytorch版吗，我用huggingface 的 transformer转换出现了问题
convert_bert_original_tf_checkpoint_to_pytorch.py
```
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file E:\Python_Files\BERT\roeberta_zh_L-24_H-1024_A-16_lm_layer\bert_model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```

**Comment by sunyilgdx** [comment]
已经转好了，是文件名错了，但是在MLM任务上还是表现得不太好
