### ISSUE TITLE
请问在Cloud TPU v3-256 上训练了24小时要花费多少美元或人民币？

### ISSUE THREAD

**Issue by Robets2020** [brightmart/roberta_zh#45]

**Comment by brightmart** [comment]
如果你直接购买，市场价格约6万(抢占式的话，约2万)。
https://cloud.google.com/tpu/pricing#single-device-pricing

**Comment by Robets2020** [comment]
> 如果你直接购买，市场价格约6万(抢占式的话，约2万)。
> https://cloud.google.com/tpu/pricing#single-device-pricing

谢谢。想问一下TPU v3-256 是TPU Pod吗？ 256是core的数量吗？

**Comment by brightmart** [comment]
没错，TPU Pod是泛称， 里面有128、256、512、1024核等等。
