### ISSUE TITLE
开源的模型中没有mask language预测层的参数，可不可以带上一起开源，万分感谢

### ISSUE THREAD

**Issue by zuofeng1997** [brightmart/roberta_zh#8]

**Comment by brightmart** [comment]
看到了。mask language预测层的参数有什么用呢？

**Comment by zuofeng1997** [comment]
可以预测特定位置的字符，在一些特定的场景中会有一些用处。在将模型转成pytorch的模型之后，也可以通过是否正确的预测mask位置的字符，来快速验证模型的转换是否成功了。

**Comment by brightmart** [comment]
好的，看来有用。这两天把它带上。

**Comment by zuofeng1997** [comment]
谢谢！

**Comment by brightmart** [comment]
模型也保存了lm的参数，请试用：
https://drive.google.com/file/d/1MmVWOGTsCdeUMfeCePDcatsui9zL3lND/view?usp=sharing

方便的时候告知lm或下游任务的效果

**Comment by ZJS007** [comment]
您好，有没有保存了lm的base和small模型的参数模型呢？我看base和small size的模型也没办法恢复mask language预测层的参数
